/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Consultas;

/**
 *
 * @author ing mariano ramos
 */
public class CONSULTADESALA extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consultas
     */
    public CONSULTADESALA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jLabelIDsala = new javax.swing.JLabel();
        jTextFieldIDsala = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabladeDatos = new javax.swing.JTable();
        jButtonRetornar = new javax.swing.JButton();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setClosable(true);
        setIconifiable(true);
        setTitle("CONSULTA DE SALA");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficas/fondo.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIDsala.setBackground(new java.awt.Color(204, 204, 255));
        jLabelIDsala.setText("ID  de Sala ");
        getContentPane().add(jLabelIDsala, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 35, 117, 30));

        jTextFieldIDsala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDsalaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIDsala, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 33, 72, 35));

        jButtonBuscar.setText("BUSCAR");
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabelNombre.setText("Nombre");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 40, 75, -1));

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 120, 35));

        jTableTabladeDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID ", "SALA", "DESCRIPCION", "LOCALIZACION"
            }
        ));
        jScrollPane1.setViewportView(jTableTabladeDatos);
        if (jTableTabladeDatos.getColumnModel().getColumnCount() > 0) {
            jTableTabladeDatos.getColumnModel().getColumn(0).setMinWidth(50);
            jTableTabladeDatos.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTableTabladeDatos.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 511, 172));

        jButtonRetornar.setText("Retornar");
        getContentPane().add(jButtonRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 307, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDsalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDsalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDsalaActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonRetornar;
    private javax.swing.JLabel jLabelIDsala;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTabladeDatos;
    private javax.swing.JTextField jTextFieldIDsala;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
