/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Movimientos;

/**
 *
 * @author ing mariano ramos
 */
public class Cuotas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cobros
     */
    public Cuotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        LabelIDcuota = new javax.swing.JLabel();
        LabelIDcliente = new javax.swing.JLabel();
        LabelFechacuota = new javax.swing.JLabel();
        labelMontocobrar = new javax.swing.JLabel();
        labelEstatuscuota = new javax.swing.JLabel();
        TextFieldMontoacobrar = new javax.swing.JTextField();
        RadioButtonActivo = new javax.swing.JRadioButton();
        RadioButtonInactivo = new javax.swing.JRadioButton();
        TextFieldFechacuota = new javax.swing.JTextField();
        TextFieldIDcuota = new javax.swing.JTextField();
        TextFieldIDcliente = new javax.swing.JTextField();
        ButtonCancelar = new javax.swing.JButton();
        ButtonAceptar = new javax.swing.JButton();

        jTextField3.setText("jTextField1");

        setBackground(new java.awt.Color(255, 204, 0));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("COBROS");

        LabelIDcuota.setText("ID de cuota");

        LabelIDcliente.setText("ID cliente");

        LabelFechacuota.setText("Fecha de cuota");

        labelMontocobrar.setText("Monto a cobrar");

        labelEstatuscuota.setText("Estatus de cuota");

        RadioButtonActivo.setBackground(new java.awt.Color(0, 255, 0));
        RadioButtonActivo.setText("ACTIVO");
        RadioButtonActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonActivoActionPerformed(evt);
            }
        });

        RadioButtonInactivo.setBackground(new java.awt.Color(255, 51, 0));
        RadioButtonInactivo.setText("INACTIVO");
        RadioButtonInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonInactivoActionPerformed(evt);
            }
        });

        TextFieldFechacuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldFechacuotaActionPerformed(evt);
            }
        });

        TextFieldIDcuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIDcuotaActionPerformed(evt);
            }
        });

        TextFieldIDcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIDclienteActionPerformed(evt);
            }
        });

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        ButtonAceptar.setText("Aceptar");
        ButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMontocobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ButtonCancelar)
                                    .addComponent(labelEstatuscuota, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RadioButtonActivo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RadioButtonInactivo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(ButtonAceptar))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextFieldMontoacobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelIDcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelFechacuota)
                                    .addComponent(LabelIDcuota, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextFieldIDcliente, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(TextFieldFechacuota)
                                    .addComponent(TextFieldIDcuota))))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextFieldIDcuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelIDcuota, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelFechacuota, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldFechacuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIDcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldIDcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMontocobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldMontoacobrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstatuscuota, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioButtonActivo)
                    .addComponent(RadioButtonInactivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCancelar)
                    .addComponent(ButtonAceptar))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioButtonActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonActivoActionPerformed

    private void RadioButtonInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonInactivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonInactivoActionPerformed

    private void TextFieldFechacuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldFechacuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldFechacuotaActionPerformed

    private void TextFieldIDcuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIDcuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIDcuotaActionPerformed

    private void TextFieldIDclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIDclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIDclienteActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    private void ButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAceptar;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JLabel LabelFechacuota;
    private javax.swing.JLabel LabelIDcliente;
    private javax.swing.JLabel LabelIDcuota;
    private javax.swing.JRadioButton RadioButtonActivo;
    private javax.swing.JRadioButton RadioButtonInactivo;
    private javax.swing.JTextField TextFieldFechacuota;
    private javax.swing.JTextField TextFieldIDcliente;
    private javax.swing.JTextField TextFieldIDcuota;
    private javax.swing.JTextField TextFieldMontoacobrar;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel labelEstatuscuota;
    private javax.swing.JLabel labelMontocobrar;
    // End of variables declaration//GEN-END:variables
}
